In [1]:
import pandas as pd 
import numpy as np

### Numpy Arrays

In [2]:
ml = [1,2,3]


In [5]:
ml1 = np.array(ml)
ml1

array([1, 2, 3])

In [7]:
ml2 = [[1,2,3], [4,5,6], [7,8,9]]
ml2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
ml22 = np.array(ml2)
ml22

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [20]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(3)

array([0.37270474, 0.37360936, 0.32952755])

In [27]:
np.random.rand(4,4)

array([[0.03923717, 0.84505406, 0.5633981 , 0.25842021],
       [0.04731813, 0.69495262, 0.70657086, 0.3579812 ],
       [0.92632597, 0.32012178, 0.43070964, 0.0084622 ],
       [0.28277473, 0.14098049, 0.57471634, 0.39569933]])

In [28]:
np.random.randn(2)

array([-0.38039585,  1.18840989])

In [29]:
np.random.randn(4,4)

array([[ 1.12465297,  1.24619785,  0.26080994,  1.14382383],
       [ 0.22454496,  0.83117584,  0.02832971, -0.95239683],
       [-1.03441461, -0.25603469,  0.38955872,  0.73911178],
       [ 0.89717727,  0.65875139, -0.16490426,  0.52475972]])

In [30]:
np.random.randint(1,100)

4

In [31]:
np.random.randint(1,100,10)

array([ 6, 83, 21, 38, 37, 48, 31, 34, 15, 28])

In [33]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr = np.arange(0,25,5)
arr


array([ 0,  5, 10, 15, 20])

In [39]:
ar1 = np.arange(25) 
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ar1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
n1 = np.random.randint(1,50,10)
n1

array([16, 14, 10, 10, 23, 36, 31, 14,  9, 21])

In [48]:
n1.max()

36

In [49]:
n1.min()

9

In [50]:
n1.argmax()

5

In [51]:
n1.argmin()

8

In [53]:
n1.shape

(10,)

In [55]:
n1.reshape(5,2)

array([[16, 14],
       [10, 10],
       [23, 36],
       [31, 14],
       [ 9, 21]])

In [59]:
n1.dtype

dtype('int32')

## Numpy Indexing and Selection

In [61]:
a1 = np.arange(0,11)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
a1[2]

2

In [65]:
a2 = np.random.randint(0,50,15)
a2

array([11, 34, 24,  3, 39, 45, 29, 26, 15, 46, 17, 19, 49,  0, 16])

In [66]:
a2[9]

46

In [67]:
a2[2:12]

array([24,  3, 39, 45, 29, 26, 15, 46, 17, 19])

In [68]:
a2[0:7] 

array([11, 34, 24,  3, 39, 45, 29])

In [69]:
a2[5:]

array([45, 29, 26, 15, 46, 17, 19, 49,  0, 16])

In [70]:
a2[1:5] = 100
a2

array([ 11, 100, 100, 100, 100,  45,  29,  26,  15,  46,  17,  19,  49,
         0,  16])

In [73]:
a2

array([ 11, 100, 100, 100, 100,  45,  29,  26,  15,  46,  17,  19,  49,
         0,  16])

In [75]:
a2_copy = a2.copy()
a2_copy[:] = 200

In [76]:
a2_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200])

In [77]:
a2

array([ 11, 100, 100, 100, 100,  45,  29,  26,  15,  46,  17,  19,  49,
         0,  16])

In [78]:
a2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
a2d[1][1]

5

In [80]:
a2d[2][2]

9

In [81]:
a2d[2,2]

9

In [86]:
a2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [96]:
a3 = np.arange(1,11)
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
a3bool = a3 > 4
a3bool

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [101]:
a3[a3bool]

array([ 5,  6,  7,  8,  9, 10])

In [103]:
a4 = np.arange(50)
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [105]:
a4 = a4.reshape(5,10)
a4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [106]:
a4[2:4,4:6]

array([[24, 25],
       [34, 35]])