In [1]:
import pandas as pd 
import numpy as np

### Numpy Arrays

In [2]:
ml = [1,2,3]


In [3]:
ml1 = np.array(ml)
ml1

array([1, 2, 3])

In [4]:
ml2 = [[1,2,3], [4,5,6], [7,8,9]]
ml2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
ml22 = np.array(ml2)
ml22

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [7]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [11]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [12]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(3)

array([0.06887629, 0.31346274, 0.70459344])

In [16]:
np.random.rand(4,4)

array([[0.19502174, 0.53765128, 0.58116019, 0.26641277],
       [0.695112  , 0.61639613, 0.69338571, 0.39704717],
       [0.36098781, 0.40487614, 0.42918869, 0.84228412],
       [0.89764294, 0.4744176 , 0.84081743, 0.79726311]])

In [17]:
np.random.randn(2)

array([-0.1737982 , -1.53082235])

In [18]:
np.random.randn(4,4)

array([[ 0.48869723,  0.65010453, -1.79525107, -0.0646785 ],
       [-0.99391901,  0.2936333 , -0.91926828, -0.71332399],
       [ 0.12519459,  0.75917705, -0.80880614, -1.60886611],
       [ 0.45664119,  0.73515738,  0.55407004,  0.13991205]])

In [19]:
np.random.randint(1,100)

19

In [20]:
np.random.randint(1,100,10)

array([78, 10, 61, 23, 74,  7, 32, 47,  1, 98])

In [21]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr = np.arange(0,25,5)
arr


array([ 0,  5, 10, 15, 20])

In [23]:
ar1 = np.arange(25) 
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ar1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
n1 = np.random.randint(1,50,10)
n1

array([46, 22, 32, 10, 40, 11, 16, 11, 20, 46])

In [26]:
n1.max()

46

In [27]:
n1.min()

10

In [28]:
n1.argmax()

0

In [29]:
n1.argmin()

3

In [30]:
n1.shape

(10,)

In [31]:
n1.reshape(5,2)

array([[46, 22],
       [32, 10],
       [40, 11],
       [16, 11],
       [20, 46]])

In [32]:
n1.dtype

dtype('int32')

## Numpy Indexing and Selection

In [33]:
a1 = np.arange(0,11)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
a1[2]

2

In [35]:
a2 = np.random.randint(0,50,15)
a2

array([ 1, 17,  0, 23, 29,  7,  6, 19, 25, 27, 38,  3, 10, 45, 13])

In [36]:
a2[9]

27

In [37]:
a2[2:12]

array([ 0, 23, 29,  7,  6, 19, 25, 27, 38,  3])

In [38]:
a2[0:7] 

array([ 1, 17,  0, 23, 29,  7,  6])

In [39]:
a2[5:]

array([ 7,  6, 19, 25, 27, 38,  3, 10, 45, 13])

In [40]:
a2[1:5] = 100
a2

array([  1, 100, 100, 100, 100,   7,   6,  19,  25,  27,  38,   3,  10,
        45,  13])

In [41]:
a2

array([  1, 100, 100, 100, 100,   7,   6,  19,  25,  27,  38,   3,  10,
        45,  13])

In [42]:
a2_copy = a2.copy()
a2_copy[:] = 200

In [43]:
a2_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200])

In [44]:
a2

array([  1, 100, 100, 100, 100,   7,   6,  19,  25,  27,  38,   3,  10,
        45,  13])

In [45]:
a2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a2d[1][1]

5

In [47]:
a2d[2][2]

9

In [48]:
a2d[2,2]

9

In [49]:
a2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [50]:
a3 = np.arange(1,11)
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
a3bool = a3 > 4
a3bool

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
a3[a3bool]

array([ 5,  6,  7,  8,  9, 10])

In [53]:
a4 = np.arange(50)
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [54]:
a4 = a4.reshape(5,10)
a4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
a4[2:4,4:6]

array([[24, 25],
       [34, 35]])

In [56]:
a4 + a4

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [57]:
a4 * a4

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401]])

In [58]:
a4 - 100

array([[-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91],
       [ -90,  -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81],
       [ -80,  -79,  -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71],
       [ -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,  -62,  -61],
       [ -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,  -51]])

In [59]:
a4/a4

<ipython-input-59-6e7cf59c888e>:1: RuntimeWarning: invalid value encountered in true_divide
  a4/a4


array([[nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [60]:
1/a4

<ipython-input-60-c102ca8ffe27>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/a4


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
        0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111],
       [0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
        0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158],
       [0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667,
        0.04      , 0.03846154, 0.03703704, 0.03571429, 0.03448276],
       [0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176,
        0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103],
       [0.025     , 0.02439024, 0.02380952, 0.02325581, 0.02272727,
        0.02222222, 0.02173913, 0.0212766 , 0.02083333, 0.02040816]])

In [61]:
np.sqrt(a4)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
        5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ],
       [6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
        6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ]])

In [62]:
np.exp(a4)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
        6.56599691e+07, 1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
        1.44625706e+12, 3.93133430e+12],
       [1.06864746e+13, 2.90488497e+13, 7.89629602e+13, 2.14643580e+14,
        5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16],
       [2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
        1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
        7.01673591e+20, 1.90734657e+21]])

In [63]:
np.max(a4)

49

In [64]:
np.sin(a4)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
         0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
        -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
        -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
         0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265]])

In [65]:
np.cos(a4)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
        -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
         0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753],
       [ 0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
        -0.90369221, -0.12796369,  0.76541405,  0.95507364,  0.26664293],
       [-0.66693806, -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,
         0.52532199, -0.43217794, -0.99233547, -0.64014434,  0.30059254]])

In [66]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [69]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [70]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [71]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [72]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.random.rand(1)

array([0.64758424])

In [75]:
np.random.randn(25)

array([ 0.38153425, -2.08168686, -0.74492257, -0.8885237 , -0.46304415,
        0.13381545, -0.34979829, -0.86025615, -1.10873479, -0.49765323,
       -0.3418555 , -0.1569772 ,  0.04947962,  0.11889633, -1.77992515,
        1.37623976,  0.91421271,  0.22265575,  0.85924541,  0.05630397,
       -0.73788032, -0.8716246 ,  0.25632816,  0.40630853, -1.29007885])

In [80]:
a6 = np.linspace(0.01,1,100)
a6.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [82]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [84]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [86]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [88]:
mat[3,4]

20

In [91]:
mat[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [94]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [93]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [95]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [96]:
mat.sum()

325

In [98]:
np.std(mat)

7.211102550927978

In [101]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])