In [1]:
import pandas as pd 
import numpy as np

### Numpy Arrays

In [2]:
ml = [1,2,3]


In [5]:
ml1 = np.array(ml)
ml1

array([1, 2, 3])

In [7]:
ml2 = [[1,2,3], [4,5,6], [7,8,9]]
ml2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
ml22 = np.array(ml2)
ml22

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [20]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(3)

array([0.37270474, 0.37360936, 0.32952755])

In [27]:
np.random.rand(4,4)

array([[0.03923717, 0.84505406, 0.5633981 , 0.25842021],
       [0.04731813, 0.69495262, 0.70657086, 0.3579812 ],
       [0.92632597, 0.32012178, 0.43070964, 0.0084622 ],
       [0.28277473, 0.14098049, 0.57471634, 0.39569933]])

In [28]:
np.random.randn(2)

array([-0.38039585,  1.18840989])

In [29]:
np.random.randn(4,4)

array([[ 1.12465297,  1.24619785,  0.26080994,  1.14382383],
       [ 0.22454496,  0.83117584,  0.02832971, -0.95239683],
       [-1.03441461, -0.25603469,  0.38955872,  0.73911178],
       [ 0.89717727,  0.65875139, -0.16490426,  0.52475972]])

In [30]:
np.random.randint(1,100)

4

In [31]:
np.random.randint(1,100,10)

array([ 6, 83, 21, 38, 37, 48, 31, 34, 15, 28])

In [33]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr = np.arange(0,25,5)
arr


array([ 0,  5, 10, 15, 20])

In [39]:
ar1 = np.arange(25) 
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ar1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
n1 = np.random.randint(1,50,10)
n1

array([16, 14, 10, 10, 23, 36, 31, 14,  9, 21])

In [48]:
n1.max()

36

In [49]:
n1.min()

9

In [50]:
n1.argmax()

5

In [51]:
n1.argmin()

8

In [53]:
n1.shape

(10,)

In [55]:
n1.reshape(5,2)

array([[16, 14],
       [10, 10],
       [23, 36],
       [31, 14],
       [ 9, 21]])

In [59]:
n1.dtype

dtype('int32')

## Numpy Indexing and Selection

In [61]:
a1 = np.arange(0,11)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
a1[2]

2

In [65]:
a2 = np.random.randint(0,50,15)
a2

array([11, 34, 24,  3, 39, 45, 29, 26, 15, 46, 17, 19, 49,  0, 16])

In [66]:
a2[9]

46

In [67]:
a2[2:12]

array([24,  3, 39, 45, 29, 26, 15, 46, 17, 19])

In [68]:
a2[0:7] 

array([11, 34, 24,  3, 39, 45, 29])

In [69]:
a2[5:]

array([45, 29, 26, 15, 46, 17, 19, 49,  0, 16])

In [70]:
a2[1:5] = 100
a2

array([ 11, 100, 100, 100, 100,  45,  29,  26,  15,  46,  17,  19,  49,
         0,  16])

In [73]:
a2

array([ 11, 100, 100, 100, 100,  45,  29,  26,  15,  46,  17,  19,  49,
         0,  16])

In [75]:
a2_copy = a2.copy()
a2_copy[:] = 200

In [76]:
a2_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200])

In [77]:
a2

array([ 11, 100, 100, 100, 100,  45,  29,  26,  15,  46,  17,  19,  49,
         0,  16])

In [78]:
a2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
a2d[1][1]

5

In [80]:
a2d[2][2]

9

In [81]:
a2d[2,2]

9

In [86]:
a2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [96]:
a3 = np.arange(1,11)
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
a3bool = a3 > 4
a3bool

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [101]:
a3[a3bool]

array([ 5,  6,  7,  8,  9, 10])

In [103]:
a4 = np.arange(50)
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [105]:
a4 = a4.reshape(5,10)
a4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [106]:
a4[2:4,4:6]

array([[24, 25],
       [34, 35]])

In [107]:
a4 + a4

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [108]:
a4 * a4

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401]])

In [110]:
a4 - 100

array([[-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91],
       [ -90,  -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81],
       [ -80,  -79,  -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71],
       [ -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,  -62,  -61],
       [ -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,  -51]])

In [111]:
a4/a4

<ipython-input-111-6e7cf59c888e>:1: RuntimeWarning: invalid value encountered in true_divide
  a4/a4


array([[nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [112]:
1/a4

<ipython-input-112-c102ca8ffe27>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/a4


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
        0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111],
       [0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
        0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158],
       [0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667,
        0.04      , 0.03846154, 0.03703704, 0.03571429, 0.03448276],
       [0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176,
        0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103],
       [0.025     , 0.02439024, 0.02380952, 0.02325581, 0.02272727,
        0.02222222, 0.02173913, 0.0212766 , 0.02083333, 0.02040816]])

In [114]:
np.sqrt(a4)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
        5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ],
       [6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
        6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ]])

In [115]:
np.exp(a4)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
        6.56599691e+07, 1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
        1.44625706e+12, 3.93133430e+12],
       [1.06864746e+13, 2.90488497e+13, 7.89629602e+13, 2.14643580e+14,
        5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16],
       [2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
        1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
        7.01673591e+20, 1.90734657e+21]])

In [116]:
np.max(a4)

49

In [117]:
np.sin(a4)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
         0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
        -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
        -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
         0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265]])

In [118]:
np.cos(a4)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
        -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
         0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753],
       [ 0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
        -0.90369221, -0.12796369,  0.76541405,  0.95507364,  0.26664293],
       [-0.66693806, -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,
         0.52532199, -0.43217794, -0.99233547, -0.64014434,  0.30059254]])